variables:
  scheme: 'YourApp'
  configuration: 'Release'
  provisioningProfileUuid: '<provisioning_profile_uuid>'
  signingCertificateUuid: '<signing_certificate_uuid>'
  signingCertificateP12: '<signing_certificate_p12>'
  signingCertificatePassword: '$(p12Password)' # Ensure you have defined this variable in the pipeline variables
  ARCHIVE_BUILD: true
  CODESIGN_STYLE: Manual
  KEYCHAIN_NAME: healthapp.keychain-db
  KEYCHAIN_PW: "encrypted token"
  START_SIMULATOR: false
  TARGET_SIMULATOR: iPhone 13
  TARGET_SIMULATOR_OS: 16.1
  TARGET_XCODE: 14.1
  APPCENTER_ACCESS_TOKEN: "encypted token"
  APPCENTER_IPA: $WORKSPACE/build/Healthapp.ipa
  APP_BUNDLE_ID: com.healthapp.abbot
  APP_GROUP: abbot.extension
  ARCHIVE_TYPE: submission_candidate
  BUILD_CONFIGURATION: Release
  CODESIGN_IDENTITY:Apple Distribution: abbot (98U349F03)
  DEV_TEAM: 98U349F03
  EXPORT_RELEASE_PLIST: exportReleasePlist.plist
  PROFILE: Abbot Health App (App Store)
